language: generic
sudo: true
os:
 - linux
 - osx
before_install:
 - ./.travis/before_install.sh
install:
 - python setup.py develop
script:
 - tox
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: cdrrma3XaFjtv4lHvag6dfhSbKBF8iLmVgPQEjXP8qa+WxHnkHObkyraYAFGqThDY/0lBdrBm7Og6l1JfAcSA2BjdPQYxujP8KEoVicPwlgwEJ5LZo4HqympWVk33APvbcYNw7K/CwEXNJCCD1tDiO4pdwkPAWuKlnYUVfZq2yI=
  on:
    tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08a570c12a3afa37d8e2

